[versions]
minecraft = "1.21.11"

# Fabric
fabric-loader = "0.18.4"
fabric-api = "0.141.2+1.21.11"
fabric-permissions = "0.6.1"

# Kotlin
kotlin = "2.3.0"
fabric-kotlin = "1.13.8+kotlin.2.3.0"

# ktoml
ktoml = "0.7.1"

# JDA
jda = "5.6.1"

[libraries]
minecraft = { module = "net.minecraft:minecraft", version.ref = "minecraft" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }
fabric-permissions = { module = "me.lucko:fabric-permissions-api", version.ref = "fabric-permissions" }

ktoml-core = { module = "com.akuleshov7:ktoml-core", version.ref = "ktoml" }
ktoml-file = { module = "com.akuleshov7:ktoml-file", version.ref = "ktoml" }

jda = { module = "net.dv8tion:JDA", version.ref = "jda" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

loom = { id = "fabric-loom", version = "1.15-SNAPSHOT" }
